version: "3.8"
services:
  mongo-db:
    image: mongo:4-focal
    container_name: go-learn
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Password1
      MONGO_USERNAME: user
      MONGO_PASSWORD: password1
    volumes:
      - './init-mongodb.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro'

  mysql-db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password1
      MYSQL_DATABASE: learn-go
      MYSQL_PASSWORD: Password1
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:

